name: Build and Deploy Slides

on:
  push:
    branches:
      - test  # Only trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use Python 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/MartenBE/mkslides.git  # Install mkslides from GitHub

    - name: Build slides
      run: |
        mkslides build docs/Money_Matters_Presentation.md  # Assuming your slides.md is inside the docs/ folder
        mkdir -p docs/build
        cp -r build/* docs/build/

    - name: Commit and push built slides
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add docs/build/
        git diff --cached --quiet || (git commit -m "Auto-build slides with MkSlides" && git push)
