name: Build and Deploy Slides

on:
  push:
    branches:
      - main  # Only trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install MkSlides
      run: |
        python -m pip install --upgrade pip
        pip install mkslides

    - name: Build slides
      run: |
        # Build the slides from the docs/ directory
        mkslides build docs/slides.md
        # Copy built content to docs/ to be served by GitHub Pages
        mkdir -p docs/build
        cp -r build/* docs/build/

    - name: Commit and push built slides
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add docs/build/
        git diff --cached --quiet || (git commit -m "Auto-build slides with MkSlides" && git push)
